// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
)

type Category struct {
	ID   []byte
	Name string
}

type Item struct {
	ID     []byte
	Period string
	Sum    sql.NullInt64
	Who    string
	Cat    []byte
}

type Pattern struct {
	ID       []byte
	Pattern  string
	Category []byte
}

type User struct {
	Name   string
	Factor sql.NullInt64
}
