// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const addCategory = `-- name: AddCategory :exec
INSERT INTO categories (id, name) VALUES(?,?)
`

type AddCategoryParams struct {
	ID   []byte
	Name string
}

func (q *Queries) AddCategory(ctx context.Context, arg AddCategoryParams) error {
	_, err := q.db.ExecContext(ctx, addCategory, arg.ID, arg.Name)
	return err
}

const addItem = `-- name: AddItem :exec
INSERT INTO items (id, period, sum,  who, cat) VALUES(?,?,?,?,?)
`

type AddItemParams struct {
	ID     []byte
	Period string
	Sum    sql.NullInt64
	Who    string
	Cat    []byte
}

func (q *Queries) AddItem(ctx context.Context, arg AddItemParams) error {
	_, err := q.db.ExecContext(ctx, addItem,
		arg.ID,
		arg.Period,
		arg.Sum,
		arg.Who,
		arg.Cat,
	)
	return err
}

const addPattern = `-- name: AddPattern :exec
INSERT INTO patterns (id, pattern, category) VALUES(?,?,?)
`

type AddPatternParams struct {
	ID       []byte
	Pattern  string
	Category []byte
}

func (q *Queries) AddPattern(ctx context.Context, arg AddPatternParams) error {
	_, err := q.db.ExecContext(ctx, addPattern, arg.ID, arg.Pattern, arg.Category)
	return err
}

const addUser = `-- name: AddUser :exec
INSERT INTO users (name, factor) VALUES(?,?)
`

type AddUserParams struct {
	Name   string
	Factor sql.NullInt64
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser, arg.Name, arg.Factor)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, period, sum, who, cat FROM items WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id []byte) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Period,
		&i.Sum,
		&i.Who,
		&i.Cat,
	)
	return i, err
}

const getPatterns = `-- name: GetPatterns :many
SELECT id, pattern, category FROM patterns
`

func (q *Queries) GetPatterns(ctx context.Context) ([]Pattern, error) {
	rows, err := q.db.QueryContext(ctx, getPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pattern
	for rows.Next() {
		var i Pattern
		if err := rows.Scan(&i.ID, &i.Pattern, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeriod = `-- name: GetPeriod :many
SELECT id,period, sum, who, cat FROM items WHERE period = ?
`

func (q *Queries) GetPeriod(ctx context.Context, period string) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getPeriod, period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Period,
			&i.Sum,
			&i.Who,
			&i.Cat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsers = `-- name: GetUsers :many
SELECT name, factor FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.Name, &i.Factor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name FROM categories
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCategory = `-- name: RemoveCategory :exec
DELETE FROM categories WHERE id = ?
`

func (q *Queries) RemoveCategory(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, removeCategory, id)
	return err
}

const removeItem = `-- name: RemoveItem :exec
DELETE FROM items WHERE id = ?
`

func (q *Queries) RemoveItem(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, removeItem, id)
	return err
}

const removePattern = `-- name: RemovePattern :exec
DELETE FROM patterns WHERE id = ?
`

func (q *Queries) RemovePattern(ctx context.Context, id []byte) error {
	_, err := q.db.ExecContext(ctx, removePattern, id)
	return err
}

const removeUser = `-- name: RemoveUser :exec
DELETE FROM users WHERE name = ?
`

func (q *Queries) RemoveUser(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, removeUser, name)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = ? WHERE id = ?
`

type UpdateCategoryParams struct {
	Name string
	ID   []byte
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory, arg.Name, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET factor = ? WHERE name = ?
`

type UpdateUserParams struct {
	Factor sql.NullInt64
	Name   string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Factor, arg.Name)
	return err
}
